[package]
name = "torrent-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = "1.0.204"
serde_bencode = "0.2.4"
serde_bytes = "0.11.15"
serde_derive = "1.0.204"
sha1 = "0.10.6"
